# Generated by Django 4.2 on 2023-05-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_reviews_quantity'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='books',
            field=models.ManyToManyField(to='books.book'),
        ),
        migrations.DeleteModel(
            name='BookForBuy',
        ),
    ]
