# Generated by Django 4.2 on 2023-05-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_review_unique_together_and_more'),
        ('purchases', '0002_shoppingcart_books_delete_bookforbuy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='books',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='books_to_purchase',
            field=models.ManyToManyField(default=None, to='books.book'),
        ),
    ]
