# Generated by Django 4.2 on 2023-05-15 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_favourites_delete_favourite'),
        ('purchases', '0003_remove_shoppingcart_books_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
