# Generated by Django 4.2 on 2023-05-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reviews_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
