# Generated by Django 4.2 on 2023-05-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
