# Generated by Django 4.2 on 2023-05-24 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='reviews_quantity',
        ),
    ]
