# Generated by Django 4.2 on 2023-05-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_reviews_quantity'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourite',
            field=models.ManyToManyField(to='books.book'),
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
