# Generated by Django 4.2 on 2023-05-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_title'),
        ('users', '0004_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, to='books.book'),
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
