# Generated by Django 4.2 on 2023-05-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_review_unique_together_and_more'),
        ('users', '0005_profile_favourites_delete_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='purchase_history',
            field=models.ManyToManyField(blank=True, default=None, related_name='purchase_history', to='books.book'),
        ),
    ]
